# Generated by Django 5.2.7 on 2025-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
