# Generated by Django 5.2.5 on 2025-10-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_programas_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programas',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
