# Generated by Django 5.2.5 on 2025-10-10 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_empresas_ativo_programas_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='programas',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
