# Generated by Django 5.2.5 on 2025-10-10 12:27

import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_empresas_datacriacao_programas_datacriacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='PlanoDeContas',
            field=models.FileField(blank=True, null=True, upload_to='planoDeContas/', validators=[galeria.models.validar_arquivo_excel]),
        ),
    ]
