# Generated by Django 5.2.5 on 2025-10-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_empresas_planodecontas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
